import { StyleSheet } from 'react-native';

export const createAccountStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F8F9FF',
  },
  keyboard: {
    flex: 1,
  },
  container: {
    minHeight: '100%',
    backgroundColor: '#F8F9FF',
  },
  topBar: {
    height: 65,
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
    backgroundColor: '#F8FAFC',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  brandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  brandText: {
    fontFamily: 'Manrope-Bold',
    fontSize: 18,
    lineHeight: 28,
    letterSpacing: -0.45,
    color: '#1B365D',
  },
  formSurface: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 24,
    paddingVertical: 44,
    shadowColor: '#1B365D',
    shadowOpacity: 0.08,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  formCard: {
    width: '100%',
    gap: 22,
  },
  headingBlock: {
    alignItems: 'center',
    gap: 8,
  },
  title: {
    fontFamily: 'Manrope-Bold',
    fontSize: 42,
    lineHeight: 44,
    letterSpacing: -0.64,
    color: '#0B1C30',
    textAlign: 'center',
  },
  subtitle: {
    fontFamily: 'Manrope-Regular',
    fontSize: 16,
    lineHeight: 24,
    color: '#44474E',
    textAlign: 'center',
  },
  fieldGroup: {
    gap: 8,
  },
  label: {
    fontFamily: 'Manrope-SemiBold',
    fontSize: 14,
    lineHeight: 16,
    letterSpacing: 0.7,
    color: '#0B1C30',
  },
  inputWrap: {
    height: 49,
    borderWidth: 1,
    borderColor: '#C4C6CF',
    borderRadius: 16,
    backgroundColor: '#F8F9FF',
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  input: {
    fontFamily: 'Manrope-Regular',
    fontSize: 16,
    lineHeight: 20,
    color: '#0B1C30',
    flex: 1,
    height: '100%',
  },
  primaryButton: {
    height: 42,
    borderRadius: 16,
    backgroundColor: '#0051D5',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    marginTop: 4,
  },
  primaryButtonDisabled: {
    opacity: 0.55,
  },
  primaryButtonText: {
    fontFamily: 'Manrope-SemiBold',
    fontSize: 14,
    lineHeight: 16,
    letterSpacing: 0.7,
    color: '#FFFFFF',
  },
  secondaryActionRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 2,
  },
  secondaryActionText: {
    fontFamily: 'Manrope-Regular',
    fontSize: 14,
    lineHeight: 20,
    color: '#44474E',
  },
  secondaryActionLink: {
    fontFamily: 'Manrope-SemiBold',
    fontSize: 12,
    lineHeight: 16,
    color: '#0051D5',
  },
  footer: {
    height: 125,
    backgroundColor: '#F8FAFC',
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
  },
});
