import { StyleSheet } from 'react-native';

export const overviewStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#f8fafc',
  },
  container: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 8,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
    paddingTop: 8,
  },
  headerLeft: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginRight: 12,
  },
  headerAvatarImage: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#e2e8f0',
  },
  headerAvatarFallback: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#0d9488',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerAvatarInitials: {
    fontFamily: 'Manrope-SemiBold',
    fontSize: 15,
    color: '#fff',
  },
  headerTitle: {
    flex: 1,
    fontFamily: 'Manrope-Bold',
    fontSize: 18,
    color: '#0f172a',
    letterSpacing: -0.2,
  },
  headerBellHit: {
    padding: 8,
    marginRight: -4,
  },
  heading: {
    fontFamily: 'Manrope-Bold',
    fontSize: 24,
    color: '#0f172a',
    marginBottom: 8,
  },
  subheading: {
    fontFamily: 'Manrope-Regular',
    fontSize: 15,
    color: '#64748b',
  },
  summaryCard: {
    marginTop: 20,
    borderRadius: 24,
    padding: 24,
    gap: 16,
    overflow: 'hidden',
    alignSelf: 'stretch',
    maxWidth: 342,
    width: '100%',
    minHeight: 218,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.04,
    shadowRadius: 40,
    elevation: 6,
  },
  summaryGlow: {
    position: 'absolute',
    width: 192,
    height: 192,
    borderRadius: 96,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    right: -48,
    top: -48,
    zIndex: 0,
  },
  summaryTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
    zIndex: 1,
  },
  summaryPortfolioLabel: {
    flex: 1,
    fontFamily: 'Manrope-Bold',
    fontSize: 10,
    lineHeight: 15,
    letterSpacing: 1,
    textTransform: 'uppercase',
    color: 'rgba(255, 255, 255, 0.7)',
  },
  summaryChangePill: {
    paddingVertical: 4,
    paddingHorizontal: 12,
    borderRadius: 9999,
    backgroundColor: 'rgba(78, 222, 163, 0.2)',
  },
  summaryChangeText: {
    fontFamily: 'Manrope-Bold',
    fontSize: 12,
    lineHeight: 16,
    color: '#4EDEA3',
  },
  summaryAmountBlock: {
    gap: 4,
    zIndex: 1,
  },
  summaryBalance: {
    fontFamily: 'Manrope-ExtraBold',
    fontSize: 30,
    lineHeight: 36,
    letterSpacing: -0.75,
    color: '#FFFFFF',
  },
  summaryValuationCaption: {
    fontFamily: 'Manrope-Regular',
    fontSize: 14,
    lineHeight: 20,
    fontStyle: 'italic',
    color: 'rgba(255, 255, 255, 0.6)',
    opacity: 0.8,
  },
  summaryActions: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 16,
    paddingTop: 8,
    zIndex: 2,
  },
  summaryActionButton: {
    flex: 1,
    height: 46,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 12,
  },
  summaryActionButtonPressed: {
    backgroundColor: 'rgba(255, 255, 255, 0.16)',
  },
  summaryActionLabel: {
    fontFamily: 'Manrope-Bold',
    fontSize: 18,
    lineHeight: 22,
    textTransform: 'uppercase',
    color: '#FFFFFF',
  },
  card: {
    marginTop: 24,
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  cardTitle: {
    fontFamily: 'Manrope-SemiBold',
    fontSize: 16,
    color: '#0f172a',
  },
  cardBody: {
    fontFamily: 'Manrope-Regular',
    fontSize: 14,
    color: '#64748b',
    marginTop: 8,
    lineHeight: 20,
  },
});
