import { StyleSheet } from 'react-native';

export const verificationSuccessStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F8F9FF',
  },
  keyboard: {
    flex: 1,
  },
  container: {
    minHeight: '100%',
    paddingHorizontal: 24,
    paddingVertical: 48,
    justifyContent: 'center',
    backgroundColor: '#F8F9FF',
  },
  main: {
    gap: 32,
  },
  card: {
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    shadowColor: '#1B365D',
    shadowOpacity: 0.08,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 40,
    overflow: 'hidden',
    gap: 32,
  },
  topAccent: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    height: 8,
    backgroundColor: '#D6E3FF',
  },
  topAccentFill: {
    width: '75%',
    height: '100%',
    backgroundColor: '#316BF3',
  },
  iconWrap: {
    width: 96,
    height: 96,
    borderRadius: 9999,
    backgroundColor: '#D6E3FF',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#1B365D',
    shadowOpacity: 0.05,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 1,
  },
  iconInner: {
    width: 40,
    height: 40,
    borderRadius: 9999,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#001B3D',
  },
  messageBlock: {
    alignItems: 'center',
    gap: 8,
  },
  title: {
    fontFamily: 'Manrope-Bold',
    fontSize: 46,
    lineHeight: 40,
    letterSpacing: -0.64,
    color: '#0B1C30',
    textAlign: 'center',
  },
  subtitle: {
    fontFamily: 'Manrope-Regular',
    fontSize: 18,
    lineHeight: 28,
    color: '#44474E',
    textAlign: 'center',
  },
  progressTrack: {
    width: 200,
    height: 6,
    borderRadius: 9999,
    backgroundColor: '#E5EEFF',
    overflow: 'hidden',
  },
  progressFill: {
    width: '75%',
    height: '100%',
    borderRadius: 9999,
    backgroundColor: '#0051D5',
  },
  primaryButton: {
    width: '100%',
    maxWidth: 246,
    height: 48,
    borderRadius: 8,
    backgroundColor: '#0051D5',
    shadowColor: '#0051D5',
    shadowOpacity: 0.15,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  primaryButtonText: {
    fontFamily: 'Manrope-SemiBold',
    fontSize: 14,
    lineHeight: 16,
    letterSpacing: 0.7,
    color: '#FFFFFF',
  },
  footerRow: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 4,
  },
  footerText: {
    fontFamily: 'Manrope-Medium',
    fontSize: 12,
    lineHeight: 16,
    color: '#44474E',
    textAlign: 'center',
  },
});
