import { StyleSheet } from 'react-native';

export const verifyEmailStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#EFF4FF',
  },
  keyboard: {
    flex: 1,
  },
  container: {
    minHeight: '100%',
    justifyContent: 'center',
    paddingHorizontal: 24,
    paddingVertical: 48,
    backgroundColor: '#EFF4FF',
  },
  main: {
    gap: 24,
  },
  brandRow: {
    height: 28,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  brandText: {
    fontFamily: 'Manrope-SemiBold',
    fontSize: 32,
    lineHeight: 28,
    letterSpacing: -0.5,
    color: '#002046',
  },
  card: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(196, 198, 207, 0.3)',
    backgroundColor: '#FFFFFF',
    shadowColor: '#1B365D',
    shadowOpacity: 0.05,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
    padding: 24,
    gap: 24,
  },
  headerSection: {
    alignItems: 'center',
    gap: 8,
  },
  badge: {
    width: 56,
    height: 56,
    borderRadius: 9999,
    backgroundColor: '#DBE1FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    fontFamily: 'Manrope-SemiBold',
    fontSize: 24,
    lineHeight: 32,
    letterSpacing: -0.24,
    color: '#0B1C30',
    textAlign: 'center',
  },
  subtitle: {
    fontFamily: 'Manrope-Regular',
    fontSize: 16,
    lineHeight: 24,
    color: '#44474E',
    textAlign: 'center',
  },
  formSection: {
    gap: 20,
  },
  codeRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 4,
  },
  codeCell: {
    width: 45,
    height: 56,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#C4C6CF',
    backgroundColor: '#F8F9FF',
    textAlign: 'center',
    fontFamily: 'Manrope-Bold',
    fontSize: 28,
    lineHeight: 38,
    color: '#6B7280',
  },
  primaryButton: {
    height: 48,
    borderRadius: 8,
    backgroundColor: '#0051D5',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  primaryButtonDisabled: {
    opacity: 0.6,
  },
  primaryButtonText: {
    fontFamily: 'Manrope-SemiBold',
    fontSize: 14,
    lineHeight: 16,
    letterSpacing: 0.7,
    color: '#FFFFFF',
  },
  secondaryRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  secondaryText: {
    fontFamily: 'Manrope-Regular',
    fontSize: 14,
    lineHeight: 20,
    color: '#44474E',
  },
  secondaryLink: {
    fontFamily: 'Manrope-SemiBold',
    fontSize: 12,
    lineHeight: 16,
    color: '#0051D5',
  },
  backRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  backText: {
    fontFamily: 'Manrope-SemiBold',
    fontSize: 12,
    lineHeight: 16,
    color: '#44474E',
    textAlign: 'center',
  },
});
